/**
 * Fictional members for demos, App Review, and end-to-end tests. Every person
 * here is invented: names, employers' staff, schools' alumni, and biographies
 * are not real people. Employers and schools are real Atlanta institutions used
 * only as plausible settings. This file is the single source of truth for
 * supabase/seed_demo.sql (generated by scripts/generate-seed.ts).
 */
import type { Education, Employment, Industry, Lifestyle, RaceEthnicity, RaceEthnicityDisclosure, RelationshipIntent, StudentStatus } from '../types/profile';
import type { VerificationData } from '../types/verification';
import type { Preferences } from '../types/preferences';

export interface MockMember {
  key: string;
  email: string;
  firstName: string;
  age: number;
  heightCm: number;
  areaId: string;
  industry: Industry;
  studentStatus: StudentStatus;
  nationalities: string[];
  raceEthnicities: RaceEthnicity[];
  raceEthnicityDisclosure: RaceEthnicityDisclosure;
  languages: string[];
  relationshipIntent: RelationshipIntent;
  lifestyle: Lifestyle;
  interests: string[];
  bio: string;
  education: Education;
  employment: Employment;
  verification: VerificationData;
  preferences: Partial<Preferences>;
  maxDistanceMiles: number;
  joinedDaysAgo: number;
  lastActiveDaysAgo: number;
  /** Only accounts meant to sign in get an auth identity. */
  canLogin: boolean;
}

export const DEMO_PASSWORD = 'review123';
export const REVIEW_EMAIL = 'review@peaches.app';

const v = (identity: VerificationData['identity'], education: VerificationData['education'], student: VerificationData['student'], employment: VerificationData['employment']): VerificationData => ({ identity, education, student, employment });

export const PEOPLE: MockMember[] = [
  {
    key: 'jordan', email: REVIEW_EMAIL, firstName: 'Jordan', age: 31, heightCm: 178, areaId: 'midtown-atlanta',
    industry: 'design_creative', studentStatus: 'professional', nationalities: ['US'], raceEthnicities: [], raceEthnicityDisclosure: 'prefer_not_to_say',
    languages: ['en', 'es'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'open' },
    interests: ['Design', 'Running', 'Coffee', 'Museums', 'Film', 'BeltLine walks'],
    bio: 'Product designer who moved to Midtown for the walkability and stayed for the people. Weekends are for long runs on the BeltLine, a museum if it rains, and cooking for whoever shows up.',
    education: { school: 'Savannah College of Art and Design', degreeLevel: 'bachelor', fieldOfStudy: 'Interaction Design', graduationYear: 2017, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Product designer', employer: 'Greenlight', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 26, max: 36 }, relationshipIntent: { strength: 'preferred', values: ['long_term', 'marriage_minded', 'intentional_dating'] }, smoking: { strength: 'required', values: ['never', 'socially'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 40, lastActiveDaysAgo: 0, canLogin: true,
  },
  {
    key: 'priya', email: 'priya@peaches.app', firstName: 'Priya', age: 29, heightCm: 163, areaId: 'decatur',
    industry: 'medicine_health', studentStatus: 'professional', nationalities: ['IN', 'US'], raceEthnicities: ['south_asian'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'hi', 'gu'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'wants_children' },
    interests: ['Running', 'Cooking', 'Podcasts', 'Museums', 'Tennis'],
    bio: 'Internal medicine resident at Emory. I keep odd hours and an ambitious reading list. Happiest at the Decatur farmers market on a rare free Saturday.',
    education: { school: 'Emory University', degreeLevel: 'professional', fieldOfStudy: 'Medicine', graduationYear: 2023, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Physician resident', employer: 'Emory Healthcare', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'required', min: 27, max: 38 }, relationshipIntent: { strength: 'preferred', values: ['long_term', 'marriage_minded'] } },
    maxDistanceMiles: 20, joinedDaysAgo: 60, lastActiveDaysAgo: 0, canLogin: false,
  },
  {
    key: 'marcus', email: 'marcus@peaches.app', firstName: 'Marcus', age: 33, heightCm: 185, areaId: 'west-end',
    industry: 'law', studentStatus: 'professional', nationalities: ['US'], raceEthnicities: ['black_african_descent'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en'], relationshipIntent: 'marriage_minded',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'sometimes', children: 'wants_children' },
    interests: ['Jazz', 'Braves games', 'Reading', 'Golf', 'Faith'],
    bio: 'Litigator by day, amateur jazz historian by night. Morehouse man, West End loyalist. Looking for someone who takes the long view.',
    education: { school: 'University of Georgia School of Law', degreeLevel: 'professional', fieldOfStudy: 'Law', graduationYear: 2018, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Attorney', employer: 'King & Spalding', employmentStatus: 'employed', publicEmployerDisplayEnabled: false },
    verification: v('verified', 'unverified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 26, max: 34 }, children: { strength: 'preferred', values: ['wants_children', 'open'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 90, lastActiveDaysAgo: 1, canLogin: false,
  },
  {
    key: 'elena', email: 'elena@peaches.app', firstName: 'Elena', age: 27, heightCm: 168, areaId: 'buckhead',
    industry: 'consulting', studentStatus: 'professional', nationalities: ['MX', 'US'], raceEthnicities: ['hispanic_latino'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'es'], relationshipIntent: 'intentional_dating',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'daily', children: 'open' },
    interests: ['Pilates', 'Travel', 'Wine', 'Farmers markets', 'Photography', 'Running'],
    bio: 'Strategy consultant, Georgia Tech engineer underneath. Training for the Peachtree, collecting good taquerias, and trying to read more fiction than spreadsheets.',
    education: { school: 'Georgia Institute of Technology', degreeLevel: 'bachelor', fieldOfStudy: 'Industrial Engineering', graduationYear: 2021, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Strategy consultant', employer: 'Deloitte', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 27, max: 35 }, languages: { strength: 'preferred', values: ['es'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 30, lastActiveDaysAgo: 0, canLogin: true,
  },
  {
    key: 'daniel', email: 'daniel@peaches.app', firstName: 'Daniel', age: 30, heightCm: 176, areaId: 'alpharetta',
    industry: 'technology', studentStatus: 'professional', nationalities: ['KR', 'US'], raceEthnicities: ['east_asian'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'ko'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'open' },
    interests: ['Tennis', 'Coffee', 'Board games', 'Hiking', 'Film'],
    bio: 'Software engineer, tennis 4.0 on a good day. I make a serious pour-over and a mediocre kimchi jjigae. Would like to fix the second one with company.',
    education: { school: 'Georgia Institute of Technology', degreeLevel: 'master', fieldOfStudy: 'Computer Science', graduationYear: 2019, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Software engineer', employer: 'Mailchimp', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'unverified'),
    preferences: { ageRange: { strength: 'preferred', min: 25, max: 33 }, interests: { strength: 'preferred', values: ['Tennis', 'Hiking', 'Coffee'] } },
    maxDistanceMiles: 40, joinedDaysAgo: 75, lastActiveDaysAgo: 2, canLogin: false,
  },
  {
    key: 'amara', email: 'amara@peaches.app', firstName: 'Amara', age: 26, heightCm: 170, areaId: 'midtown-atlanta',
    industry: 'education_research', studentStatus: 'graduate', nationalities: ['NG', 'US'], raceEthnicities: ['black_african_descent'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'yo'], relationshipIntent: 'intentional_dating',
    lifestyle: { drinking: 'never', smoking: 'never', exercise: 'sometimes', children: 'open' },
    interests: ['Volunteering', 'Live music', 'Cooking', 'Reading', 'Yoga'],
    bio: 'MPH student at Georgia State, thesis on maternal health in the metro. I volunteer Saturdays, cook Sundays, and go to too many shows on weeknights.',
    education: { school: 'Georgia State University', degreeLevel: 'master', fieldOfStudy: 'Public Health', graduationYear: 2027, currentlyEnrolled: true, publicDisplayEnabled: true },
    employment: { occupation: 'Graduate research assistant', employer: 'Georgia State University', employmentStatus: 'student', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'unverified', 'verified', 'unverified'),
    preferences: { ageRange: { strength: 'preferred', min: 25, max: 33 }, drinking: { strength: 'preferred', values: ['never', 'socially'] } },
    maxDistanceMiles: 15, joinedDaysAgo: 8, lastActiveDaysAgo: 0, canLogin: false,
  },
  {
    key: 'thomas', email: 'thomas@peaches.app', firstName: 'Thomas', age: 35, heightCm: 183, areaId: 'roswell',
    industry: 'architecture_construction', studentStatus: 'professional', nationalities: ['US'], raceEthnicities: ['white'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en'], relationshipIntent: 'marriage_minded',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'wants_children' },
    interests: ['Architecture', 'Cycling', 'Photography', 'Sailing', 'Design'],
    bio: 'Architect working on schools and libraries, which is the good kind of architecture. Cyclist, Lake Lanier sailor, patient cook.',
    education: { school: 'Georgia Institute of Technology', degreeLevel: 'master', fieldOfStudy: 'Architecture', graduationYear: 2016, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Architect', employer: 'Perkins&Will', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 28, max: 36 }, relationshipIntent: { strength: 'required', values: ['marriage_minded', 'long_term'] } },
    maxDistanceMiles: 30, joinedDaysAgo: 120, lastActiveDaysAgo: 3, canLogin: false,
  },
  {
    key: 'mei', email: 'mei@peaches.app', firstName: 'Mei', age: 31, heightCm: 160, areaId: 'johns-creek',
    industry: 'medicine_health', studentStatus: 'professional', nationalities: ['CN', 'US'], raceEthnicities: ['east_asian'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'zh'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'never', smoking: 'never', exercise: 'sometimes', children: 'wants_children' },
    interests: ['Baking', 'Gardening', 'Museums', 'Languages', 'Hiking'],
    bio: 'Clinical pharmacist. I bake on a schedule, garden without one, and am slowly learning Italian for no practical reason.',
    education: { school: 'University of Georgia', degreeLevel: 'professional', fieldOfStudy: 'Pharmacy', graduationYear: 2019, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Clinical pharmacist', employer: 'Piedmont Healthcare', employmentStatus: 'employed', publicEmployerDisplayEnabled: false },
    verification: v('verified', 'verified', 'unverified', 'pending'),
    preferences: { ageRange: { strength: 'preferred', min: 29, max: 38 }, smoking: { strength: 'required', values: ['never'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 45, lastActiveDaysAgo: 1, canLogin: false,
  },
  {
    key: 'andre', email: 'andre@peaches.app', firstName: 'Andre', age: 28, heightCm: 180, areaId: 'east-atlanta',
    industry: 'education_research', studentStatus: 'professional', nationalities: ['US', 'HT'], raceEthnicities: ['black_african_descent'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'ht', 'fr'], relationshipIntent: 'open_to_possibilities',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'open' },
    interests: ['Soccer', 'Podcasts', 'Live music', 'Mentoring', 'Film'],
    bio: 'High school history teacher and assistant soccer coach. I will talk about Reconstruction or the Premier League for as long as you let me.',
    education: { school: 'Georgia State University', degreeLevel: 'bachelor', fieldOfStudy: 'History', graduationYear: 2020, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'High school teacher', employer: 'Atlanta Public Schools', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'unverified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 24, max: 32 } },
    maxDistanceMiles: 20, joinedDaysAgo: 20, lastActiveDaysAgo: 0, canLogin: false,
  },
  {
    key: 'sofia', email: 'sofia@peaches.app', firstName: 'Sofia', age: 24, heightCm: 165, areaId: 'athens',
    industry: 'sales_marketing', studentStatus: 'undergraduate', nationalities: ['BR'], raceEthnicities: ['mixed_multiracial'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'pt', 'es'], relationshipIntent: 'open_to_possibilities',
    lifestyle: { drinking: 'socially', smoking: 'socially', exercise: 'often', children: 'open' },
    interests: ['Travel', 'Photography', 'Live music', 'Running', 'Coffee'],
    bio: 'UGA senior in marketing, Sao Paulo originally. Finishing a thesis on independent music venues, which is a great excuse to go to shows.',
    education: { school: 'University of Georgia', degreeLevel: 'bachelor', fieldOfStudy: 'Marketing', graduationYear: 2027, currentlyEnrolled: true, publicDisplayEnabled: true },
    employment: { occupation: 'Marketing intern', employer: 'Georgia Theatre', employmentStatus: 'student', publicEmployerDisplayEnabled: true },
    verification: v('unverified', 'unverified', 'verified', 'unverified'),
    preferences: { ageRange: { strength: 'preferred', min: 23, max: 30 } },
    maxDistanceMiles: 60, joinedDaysAgo: 5, lastActiveDaysAgo: 0, canLogin: false,
  },
  {
    key: 'nathan', email: 'nathan@peaches.app', firstName: 'Nathan', age: 37, heightCm: 188, areaId: 'sandy-springs',
    industry: 'finance', studentStatus: 'professional', nationalities: ['US'], raceEthnicities: ['white'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en'], relationshipIntent: 'marriage_minded',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'has_children' },
    interests: ['Golf', 'Investing', 'Wine', 'Braves games', 'Reading'],
    bio: 'Finance director, dad to a seven-year-old every other week, early riser. Looking for a real partner, not a project.',
    education: { school: 'Emory University', degreeLevel: 'master', fieldOfStudy: 'Business Administration', graduationYear: 2015, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Finance director', employer: 'Truist', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 30, max: 40 }, children: { strength: 'preferred', values: ['has_children', 'open', 'wants_children'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 150, lastActiveDaysAgo: 9, canLogin: false,
  },
  {
    key: 'layla', email: 'layla@peaches.app', firstName: 'Layla', age: 30, heightCm: 167, areaId: 'brookhaven',
    industry: 'technology', studentStatus: 'professional', nationalities: ['LB', 'US'], raceEthnicities: ['middle_eastern_north_african'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'ar', 'fr'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'sometimes', children: 'wants_children' },
    interests: ['Design', 'Museums', 'Cooking', 'Travel', 'Board games'],
    bio: 'UX researcher who asks a lot of questions professionally and socially. Beirut-born, Brookhaven-based. My kibbeh is better than my board game record.',
    education: { school: 'Georgia Institute of Technology', degreeLevel: 'master', fieldOfStudy: 'Human-Computer Interaction', graduationYear: 2020, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'UX researcher', employer: 'NCR Voyix', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 28, max: 37 }, relationshipIntent: { strength: 'preferred', values: ['long_term', 'marriage_minded'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 55, lastActiveDaysAgo: 0, canLogin: false,
  },
  {
    key: 'kwame', email: 'kwame@peaches.app', firstName: 'Kwame', age: 32, heightCm: 182, areaId: 'smyrna',
    industry: 'engineering', studentStatus: 'professional', nationalities: ['GH', 'US'], raceEthnicities: ['black_african_descent'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'never', smoking: 'never', exercise: 'daily', children: 'wants_children' },
    interests: ['Soccer', 'Running', 'Cycling', 'Faith', 'Cooking'],
    bio: 'Civil engineer on bridges you have probably driven over. Sunday church, Saturday long ride, weeknight jollof.',
    education: { school: 'Georgia Institute of Technology', degreeLevel: 'bachelor', fieldOfStudy: 'Civil Engineering', graduationYear: 2016, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Civil engineer', employer: 'Georgia Department of Transportation', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'unverified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 26, max: 34 }, drinking: { strength: 'preferred', values: ['never', 'socially'] } },
    maxDistanceMiles: 30, joinedDaysAgo: 65, lastActiveDaysAgo: 4, canLogin: false,
  },
  {
    key: 'hannah', email: 'hannah@peaches.app', firstName: 'Hannah', age: 29, heightCm: 172, areaId: 'virginia-highland',
    industry: 'nonprofit', studentStatus: 'professional', nationalities: ['US'], raceEthnicities: ['white'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'es'], relationshipIntent: 'intentional_dating',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'open' },
    interests: ['Volunteering', 'Gardening', 'Farmers markets', 'Hiking', 'Dogs'],
    bio: 'Program director at a food bank, owner of a very opinionated hound named Biscuit. Grows tomatoes, hikes Kennesaw Mountain, reads on the porch.',
    education: { school: 'Agnes Scott College', degreeLevel: 'bachelor', fieldOfStudy: 'Sociology', graduationYear: 2019, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Program director', employer: 'Atlanta Community Food Bank', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'unverified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 27, max: 36 }, interests: { strength: 'preferred', values: ['Dogs', 'Hiking', 'Volunteering'] } },
    maxDistanceMiles: 20, joinedDaysAgo: 35, lastActiveDaysAgo: 0, canLogin: false,
  },
  {
    key: 'ravi', email: 'ravi@peaches.app', firstName: 'Ravi', age: 34, heightCm: 175, areaId: 'duluth',
    industry: 'entrepreneurship', studentStatus: 'professional', nationalities: ['IN'], raceEthnicities: ['south_asian'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'hi', 'ta'], relationshipIntent: 'marriage_minded',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'wants_children' },
    interests: ['Startups', 'Tennis', 'Podcasts', 'Investing', 'Cooking', 'Chess'],
    bio: 'Founder of a logistics software company out of Duluth. Chess on the phone, tennis on Sundays, a serious South Indian breakfast when time allows.',
    education: { school: 'Georgia Institute of Technology', degreeLevel: 'master', fieldOfStudy: 'Supply Chain Engineering', graduationYear: 2017, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Founder', employer: 'Northline Logistics', employmentStatus: 'self_employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'unverified', 'unverified', 'pending'),
    preferences: { ageRange: { strength: 'preferred', min: 27, max: 35 }, relationshipIntent: { strength: 'required', values: ['marriage_minded', 'long_term'] } },
    maxDistanceMiles: 40, joinedDaysAgo: 100, lastActiveDaysAgo: 2, canLogin: false,
  },
  {
    key: 'grace', email: 'grace@peaches.app', firstName: 'Grace', age: 25, heightCm: 166, areaId: 'midtown-atlanta',
    industry: 'law', studentStatus: 'graduate', nationalities: ['US'], raceEthnicities: ['black_african_descent'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en'], relationshipIntent: 'intentional_dating',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'sometimes', children: 'open' },
    interests: ['Reading', 'Theater', 'Museums', 'Pilates', 'Writing'],
    bio: 'Second-year law student at Emory, Spelman before that. I write essays no one asked for and see every play at the Alliance.',
    education: { school: 'Emory University School of Law', degreeLevel: 'professional', fieldOfStudy: 'Law', graduationYear: 2027, currentlyEnrolled: true, publicDisplayEnabled: true },
    employment: { occupation: 'Law student', employer: 'Emory University', employmentStatus: 'student', publicEmployerDisplayEnabled: false },
    verification: v('verified', 'unverified', 'verified', 'unverified'),
    preferences: { ageRange: { strength: 'preferred', min: 25, max: 32 } },
    maxDistanceMiles: 15, joinedDaysAgo: 12, lastActiveDaysAgo: 1, canLogin: false,
  },
  {
    key: 'julian', email: 'julian@peaches.app', firstName: 'Julian', age: 36, heightCm: 177, areaId: 'inman-park',
    industry: 'hospitality', studentStatus: 'professional', nationalities: ['CO', 'US'], raceEthnicities: ['hispanic_latino'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'es'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'socially', smoking: 'socially', exercise: 'often', children: 'has_children' },
    interests: ['Cooking', 'Farmers markets', 'Wine', 'Live music', 'Soccer'],
    bio: 'Chef and owner of a small Colombian place in Inman Park. Dad to a nine-year-old on weekends. I cook for a living and still cook to relax.',
    education: { school: 'Le Cordon Bleu Atlanta', degreeLevel: 'associate', fieldOfStudy: 'Culinary Arts', graduationYear: 2012, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Chef and owner', employer: 'Casa Arepa', employmentStatus: 'self_employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'unverified', 'unverified', 'unverified'),
    preferences: { ageRange: { strength: 'preferred', min: 29, max: 40 }, children: { strength: 'preferred', values: ['has_children', 'open'] } },
    maxDistanceMiles: 20, joinedDaysAgo: 80, lastActiveDaysAgo: 6, canLogin: false,
  },
  {
    key: 'nora', email: 'nora@peaches.app', firstName: 'Nora', age: 28, heightCm: 171, areaId: 'dunwoody',
    industry: 'technology', studentStatus: 'professional', nationalities: ['US'], raceEthnicities: ['white'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en'], relationshipIntent: 'long_term',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'daily', children: 'open' },
    interests: ['Running', 'Climbing', 'Podcasts', 'Chess', 'Coffee'],
    bio: 'Data scientist at Home Depot, climber at Stone Summit, runner everywhere else. Competitive at chess, gracious in defeat, mostly.',
    education: { school: 'Georgia Institute of Technology', degreeLevel: 'master', fieldOfStudy: 'Analytics', graduationYear: 2022, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Data scientist', employer: 'The Home Depot', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 27, max: 35 }, interests: { strength: 'preferred', values: ['Running', 'Climbing', 'Chess'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 3, lastActiveDaysAgo: 0, canLogin: false,
  },
  {
    key: 'samuel', email: 'samuel@peaches.app', firstName: 'Samuel', age: 27, heightCm: 181, areaId: 'college-park',
    industry: 'aviation', studentStatus: 'professional', nationalities: ['US'], raceEthnicities: ['white'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en'], relationshipIntent: 'open_to_possibilities',
    lifestyle: { drinking: 'socially', smoking: 'never', exercise: 'often', children: 'open' },
    interests: ['Travel', 'Photography', 'Baseball', 'Hiking', 'Film'],
    bio: 'First officer at Delta, which means I know every airport coffee and very few Atlanta restaurants. Help me fix that on my days off.',
    education: { school: 'Middle Georgia State University', degreeLevel: 'bachelor', fieldOfStudy: 'Aviation Science', graduationYear: 2021, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Airline pilot', employer: 'Delta Air Lines', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'unverified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 24, max: 32 } },
    maxDistanceMiles: 40, joinedDaysAgo: 25, lastActiveDaysAgo: 5, canLogin: false,
  },
  {
    key: 'yuna', email: 'yuna@peaches.app', firstName: 'Yuna', age: 30, heightCm: 162, areaId: 'duluth',
    industry: 'medicine_health', studentStatus: 'professional', nationalities: ['KR'], raceEthnicities: ['east_asian'], raceEthnicityDisclosure: 'disclosed',
    languages: ['en', 'ko'], relationshipIntent: 'marriage_minded',
    lifestyle: { drinking: 'never', smoking: 'never', exercise: 'sometimes', children: 'wants_children' },
    interests: ['Baking', 'Yoga', 'Museums', 'Coffee', 'Dogs'],
    bio: 'Dentist in Duluth, Seoul originally, Georgia for a decade now. Yoga most mornings, a bakery project most weekends, a very small dog most of the time.',
    education: { school: 'Augusta University', degreeLevel: 'professional', fieldOfStudy: 'Dental Medicine', graduationYear: 2021, currentlyEnrolled: false, publicDisplayEnabled: true },
    employment: { occupation: 'Dentist', employer: 'Sugarloaf Family Dental', employmentStatus: 'employed', publicEmployerDisplayEnabled: true },
    verification: v('verified', 'verified', 'unverified', 'verified'),
    preferences: { ageRange: { strength: 'preferred', min: 29, max: 38 }, languages: { strength: 'preferred', values: ['ko'] }, smoking: { strength: 'required', values: ['never'] } },
    maxDistanceMiles: 25, joinedDaysAgo: 50, lastActiveDaysAgo: 1, canLogin: false,
  },
];

export interface MockPost {
  author: string;
  body: string;
  hoursAgo: number;
}

export const POSTS: MockPost[] = [
  { author: 'priya', body: 'Post-call Sunday plan: the Piedmont Park loop, then the Decatur farmers market. Anyone have a favorite stall I should not miss?', hoursAgo: 5 },
  { author: 'marcus', body: 'Finally caught the late set at St. James Live. Atlanta jazz is underrated and I will keep saying so.', hoursAgo: 14 },
  { author: 'elena', body: 'Two weeks into Peachtree training. The BeltLine at six in the morning is a completely different city.', hoursAgo: 26 },
  { author: 'thomas', body: 'Sketched the new Midtown towers from the Botanical Garden this afternoon. A few of them are actually good.', hoursAgo: 40 },
  { author: 'hannah', body: 'The food bank has a few open Saturday morning volunteer slots this month. Happy to share details if anyone wants to come along.', hoursAgo: 52 },
  { author: 'daniel', body: 'Does anyone know a coffee shop in Alpharetta that stays quiet after three? Asking for my laptop.', hoursAgo: 70 },
  { author: 'layla', body: 'Went to the High for the new photography wing. Worth the crowd, and the third floor was almost empty.', hoursAgo: 96 },
  { author: 'ravi', body: 'The Duluth H Mart food court remains the best lunch meeting venue in the metro. Open to counterarguments, politely.', hoursAgo: 120 },
  { author: 'amara', body: 'Thesis week. If anyone has a favorite study spot near Georgia State that is not the library, I am listening.', hoursAgo: 150 },
  { author: 'nora', body: 'Climbed at Stone Summit for the first time. My forearms have opinions about it.', hoursAgo: 190 },
  { author: 'jordan', body: 'Museum plan for a rainy Saturday: the High in the morning, then Ponce City Market for lunch. Room for a couple more people.', hoursAgo: 8 },
];

export interface MockIntroduction {
  from: string;
  to: string;
  note: string;
  status: 'pending' | 'accepted' | 'declined';
  daysAgo: number;
}

export const INTRODUCTIONS: MockIntroduction[] = [
  { from: 'jordan', to: 'elena', note: 'Hi Elena. Your Peachtree post caught my eye; I run the BeltLine most mornings too and could use someone to be honest about pace. Would you be up for a coffee after a Saturday run?', status: 'accepted', daysAgo: 6 },
  { from: 'daniel', to: 'jordan', note: 'Hi Jordan, I liked how you described your weekends. I am a tennis and pour-over person and would enjoy comparing notes on Midtown coffee. Open to a conversation?', status: 'accepted', daysAgo: 3 },
  { from: 'priya', to: 'jordan', note: 'Hello Jordan. Your museum-if-it-rains rule is exactly mine. I have a rare free Saturday coming up; would you want to trade recommendations over coffee in Decatur?', status: 'pending', daysAgo: 1 },
  { from: 'marcus', to: 'jordan', note: 'Jordan, I noticed film on your list. There is a Kurosawa retrospective at the Plaza this month and I would enjoy some company for it. Interested?', status: 'pending', daysAgo: 0 },
  { from: 'jordan', to: 'layla', note: 'Hi Layla. A UX researcher who cooks kibbeh sounds like someone I should meet. I design products for a living and ask too few questions; you might balance me out.', status: 'pending', daysAgo: 0 },
  { from: 'thomas', to: 'hannah', note: 'Hannah, a food bank program director with a hound named Biscuit is a very good sentence. I would love to hear how the Saturday shifts work and maybe join one.', status: 'accepted', daysAgo: 10 },
  { from: 'kwame', to: 'amara', note: 'Amara, your thesis topic matters a lot to me; my sister is a midwife in Accra. Would you be open to a conversation about it over jollof, my cooking, no pressure?', status: 'pending', daysAgo: 2 },
  { from: 'nathan', to: 'mei', note: 'Mei, I admire anyone who bakes on a schedule. I am a finance person who gardens badly; would you be open to comparing notes some evening?', status: 'declined', daysAgo: 12 },
];

export interface MockMessage {
  from: string;
  to: string;
  body: string;
  hoursAgo: number;
}

export const MESSAGES: MockMessage[] = [
  { from: 'elena', to: 'jordan', body: 'Coffee after a Saturday run sounds perfect. Fair warning, my Saturday pace is honest but slow.', hoursAgo: 120 },
  { from: 'jordan', to: 'elena', body: 'Slow and honest is my favorite pace. Nine at the Old Fourth Ward skatepark entrance?', hoursAgo: 118 },
  { from: 'elena', to: 'jordan', body: 'Nine works. I will be the one stretching dramatically.', hoursAgo: 117 },
  { from: 'jordan', to: 'elena', body: 'Perfect. See you there.', hoursAgo: 116 },
  { from: 'hannah', to: 'thomas', body: 'The Saturday shift is 8 to 11, mostly sorting produce. Biscuit is not allowed but sends regards.', hoursAgo: 200 },
  { from: 'thomas', to: 'hannah', body: 'Count me in for the next one. Regards returned to Biscuit.', hoursAgo: 196 },
];

export interface MockSave {
  by: string;
  postAuthor: string;
}

export const SAVES: MockSave[] = [{ by: 'jordan', postAuthor: 'hannah' }, { by: 'jordan', postAuthor: 'layla' }];
