/**
 * Generates supabase/seed_demo.sql from the fictional dataset in
 * packages/core/src/mock/people.ts. Run: npm run seed:generate
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  DEGREE_SHORT_LABEL,
  DEMO_PASSWORD,
  INTRODUCTIONS,
  LEGAL_VERSIONS,
  MESSAGES,
  PEOPLE,
  POSTS,
  REVIEW_EMAIL,
  SAVES,
  areaById,
  defaultPreferences,
  type MockMember,
} from '@peaches/core';

const q = (s: string): string => `'${s.replace(/'/g, "''")}'`;
const json = (value: unknown): string => `$peaches$${JSON.stringify(value)}$peaches$::jsonb`;

const byKey = new Map(PEOPLE.map((p) => [p.key, p]));
const emailOf = (key: string): string => {
  const p = byKey.get(key);
  if (!p) throw new Error(`Unknown member key ${key}`);
  return p.email;
};

function memberPayload(m: MockMember): Record<string, unknown> {
  const area = areaById(m.areaId);
  if (!area) throw new Error(`Unknown area ${m.areaId} for ${m.key}`);
  const degree = [DEGREE_SHORT_LABEL[m.education.degreeLevel], m.education.fieldOfStudy].filter(Boolean).join(', ');
  return {
    email: m.email,
    password: DEMO_PASSWORD,
    can_login: m.canLogin,
    first_name: m.firstName,
    age: m.age,
    area_id: m.areaId,
    city: area.name,
    occupation: m.employment.occupation,
    employer: m.employment.employer,
    employment_status: m.employment.employmentStatus,
    employer_display_enabled: m.employment.publicEmployerDisplayEnabled,
    school: m.education.school,
    degree,
    degree_level: m.education.degreeLevel,
    field_of_study: m.education.fieldOfStudy,
    graduation_year: m.education.graduationYear,
    currently_enrolled: m.education.currentlyEnrolled,
    education_display_enabled: m.education.publicDisplayEnabled,
    bio: m.bio,
    terms_version: LEGAL_VERSIONS.terms,
    privacy_version: LEGAL_VERSIONS.privacy,
    height_cm: m.heightCm,
    industry: m.industry,
    student_status: m.studentStatus,
    nationalities: m.nationalities,
    race_ethnicities: m.raceEthnicityDisclosure === 'disclosed' ? m.raceEthnicities : [],
    race_ethnicity_disclosure: m.raceEthnicityDisclosure,
    languages: m.languages,
    relationship_intent: m.relationshipIntent,
    lifestyle: m.lifestyle,
    interests: m.interests,
    verification: m.verification,
    prefs: { ...defaultPreferences(), ...m.preferences },
    max_distance_miles: m.maxDistanceMiles,
    joined_days_ago: m.joinedDaysAgo,
    last_active_days_ago: m.lastActiveDaysAgo,
  };
}

const out: string[] = [];
out.push(`-- ============================================================================
-- seed_demo.sql: fictional members for demos, App Review, and development.
-- GENERATED by scripts/generate-seed.ts from packages/core/src/mock/people.ts.
-- Do not edit by hand; edit the dataset and run: npm run seed:generate
--
-- Run in the Supabase SQL Editor AFTER migrations 001-013 (and seed_admin.sql).
--
-- App Review account (put in App Store Connect review notes):
--   email:    ${REVIEW_EMAIL}
--   password: ${DEMO_PASSWORD}
--
-- One other account can sign in for two-sided testing in development:
--   email:    elena@peaches.app
--   password: ${DEMO_PASSWORD}
-- Every other member has no login identity and cannot sign in.
--
-- Every person here is fictional. Idempotent: safe to re-run. To remove, delete
-- the auth.users rows whose email ends in @peaches.app (cascades everywhere).
-- ============================================================================

create or replace function pg_temp.seed_member(p jsonb) returns uuid
language plpgsql as $$
declare
  uid uuid;
begin
  select id into uid from auth.users where email = p ->> 'email';
  if uid is null then
    uid := gen_random_uuid();
    insert into public.applications (
      email, first_name, age, area_id, city, profession, company, school, degree, bio, why,
      status, decided_at, age_confirmed, terms_version, privacy_version, consented_at
    ) values (
      p ->> 'email', p ->> 'first_name', (p ->> 'age')::integer, p ->> 'area_id', p ->> 'city',
      p ->> 'occupation', p ->> 'employer', p ->> 'school', p ->> 'degree', p ->> 'bio', 'Seed member.',
      'approved', now(), true, p ->> 'terms_version', p ->> 'privacy_version', now()
    );
    insert into auth.users (
      instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
      created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin,
      confirmation_token, email_change, email_change_token_new, recovery_token
    ) values (
      '00000000-0000-0000-0000-000000000000', uid, 'authenticated', 'authenticated',
      p ->> 'email', crypt(p ->> 'password', gen_salt('bf')), now(),
      now(), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, false,
      '', '', '', ''
    );
    if (p ->> 'can_login')::boolean then
      insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
      values (
        gen_random_uuid(), uid,
        jsonb_build_object('sub', uid::text, 'email', p ->> 'email', 'email_verified', true),
        'email', uid::text, now(), now(), now()
      );
    end if;
  end if;

  update public.profiles
     set height_cm = (p ->> 'height_cm')::integer,
         industry = p ->> 'industry',
         student_status = p ->> 'student_status',
         nationalities = array(select jsonb_array_elements_text(p -> 'nationalities')),
         race_ethnicities = array(select jsonb_array_elements_text(p -> 'race_ethnicities')),
         race_ethnicity_disclosure = p ->> 'race_ethnicity_disclosure',
         languages = array(select jsonb_array_elements_text(p -> 'languages')),
         relationship_intent = p ->> 'relationship_intent',
         lifestyle = p -> 'lifestyle',
         interests = array(select jsonb_array_elements_text(p -> 'interests')),
         bio = p ->> 'bio',
         verification_identity = p -> 'verification' ->> 'identity',
         verification_education = p -> 'verification' ->> 'education',
         verification_student = p -> 'verification' ->> 'student',
         verification_employment = p -> 'verification' ->> 'employment',
         onboarding_complete = true,
         suspended_at = null,
         created_at = now() - make_interval(days => (p ->> 'joined_days_ago')::integer),
         last_active_at = now() - make_interval(days => (p ->> 'last_active_days_ago')::integer),
         updated_at = now()
   where id = uid;

  insert into public.member_private (user_id) values (uid) on conflict (user_id) do nothing;
  update public.member_private
     set area_id = p ->> 'area_id',
         max_distance_miles = (p ->> 'max_distance_miles')::integer,
         school = p ->> 'school',
         degree_level = p ->> 'degree_level',
         field_of_study = p ->> 'field_of_study',
         graduation_year = (p ->> 'graduation_year')::integer,
         currently_enrolled = (p ->> 'currently_enrolled')::boolean,
         education_display_enabled = (p ->> 'education_display_enabled')::boolean,
         occupation = p ->> 'occupation',
         employer = p ->> 'employer',
         employment_status = p ->> 'employment_status',
         employer_display_enabled = (p ->> 'employer_display_enabled')::boolean
   where user_id = uid;

  insert into public.member_preferences (user_id, prefs) values (uid, p -> 'prefs')
  on conflict (user_id) do update set prefs = excluded.prefs, updated_at = now();

  insert into public.recommendation_signals (profile_id) values (uid)
  on conflict (profile_id) do nothing;

  return uid;
end;
$$;

create or replace function pg_temp.member_id(p_email text) returns uuid
language sql as $$ select id from auth.users where email = p_email $$;

create or replace function pg_temp.seed_post(p_email text, p_body text, p_hours_ago integer) returns void
language plpgsql as $$
declare
  uid uuid := pg_temp.member_id(p_email);
begin
  if uid is null then return; end if;
  if not exists (select 1 from public.posts where author_id = uid and body = p_body) then
    insert into public.posts (author_id, body, created_at)
    values (uid, p_body, now() - make_interval(hours => p_hours_ago));
  end if;
end;
$$;

create or replace function pg_temp.seed_intro(p_from text, p_to text, p_note text, p_status text, p_days_ago integer) returns void
language plpgsql as $$
declare
  a uuid := pg_temp.member_id(p_from);
  b uuid := pg_temp.member_id(p_to);
  rid uuid;
begin
  if a is null or b is null then return; end if;
  select id into rid from public.introduction_requests
   where requester_id = a and recipient_id = b;
  if rid is null then
    insert into public.introduction_requests (requester_id, recipient_id, note, created_at)
    values (a, b, p_note, now() - make_interval(days => p_days_ago))
    returning id into rid;
  end if;
  if p_status <> 'pending' then
    update public.introduction_requests set status = p_status where id = rid and status = 'pending';
  end if;
end;
$$;

create or replace function pg_temp.seed_message(p_from text, p_to text, p_body text, p_hours_ago integer) returns void
language plpgsql as $$
declare
  a uuid := pg_temp.member_id(p_from);
  b uuid := pg_temp.member_id(p_to);
  mid uuid;
begin
  if a is null or b is null then return; end if;
  select id into mid from public.matches
   where (user_a = a and user_b = b) or (user_a = b and user_b = a);
  if mid is null then return; end if;
  if not exists (select 1 from public.messages where match_id = mid and sender_id = a and body = p_body) then
    insert into public.messages (match_id, sender_id, body, created_at, read_at)
    values (mid, a, p_body, now() - make_interval(hours => p_hours_ago),
            case when a <> pg_temp.member_id(${q(REVIEW_EMAIL)}) then null else now() end);
  end if;
end;
$$;

create or replace function pg_temp.seed_save(p_by text, p_author text) returns void
language plpgsql as $$
declare
  a uuid := pg_temp.member_id(p_by);
  b uuid := pg_temp.member_id(p_author);
  pid uuid;
begin
  if a is null or b is null then return; end if;
  select id into pid from public.posts where author_id = b order by created_at desc limit 1;
  if pid is null then return; end if;
  insert into public.post_saves (user_id, post_id) values (a, pid) on conflict do nothing;
end;
$$;
`);

out.push('-- Members ------------------------------------------------------------------');
for (const m of PEOPLE) {
  out.push(`select pg_temp.seed_member(${json(memberPayload(m))});`);
}

out.push('\n-- Posts --------------------------------------------------------------------');
for (const p of POSTS) {
  out.push(`select pg_temp.seed_post(${q(emailOf(p.author))}, ${q(p.body)}, ${p.hoursAgo});`);
}

out.push('\n-- Introductions (accepted ones open a connection through the trigger) -----');
for (const i of INTRODUCTIONS) {
  out.push(`select pg_temp.seed_intro(${q(emailOf(i.from))}, ${q(emailOf(i.to))}, ${q(i.note)}, ${q(i.status)}, ${i.daysAgo});`);
}

out.push('\n-- Messages -----------------------------------------------------------------');
for (const msg of MESSAGES) {
  out.push(`select pg_temp.seed_message(${q(emailOf(msg.from))}, ${q(emailOf(msg.to))}, ${q(msg.body)}, ${msg.hoursAgo});`);
}

out.push('\n-- Saved posts --------------------------------------------------------------');
for (const s of SAVES) {
  out.push(`select pg_temp.seed_save(${q(emailOf(s.by))}, ${q(emailOf(s.postAuthor))});`);
}

out.push(`
-- Verify
select count(*) filter (where u.email like '%@peaches.app') as demo_members,
       (select count(*) from public.posts) as posts,
       (select count(*) from public.introduction_requests) as requests,
       (select count(*) from public.matches) as connections,
       (select count(*) from public.messages) as messages
  from auth.users u;
`);

const target = resolve(process.cwd(), 'supabase/seed_demo.sql');
writeFileSync(target, out.join('\n') + '\n');
console.log(`wrote ${target} (${PEOPLE.length} members, ${POSTS.length} posts, ${INTRODUCTIONS.length} introductions)`);
